version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/webservice
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: script/beforeInstall.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: script/afterInstallation.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: script/runfile.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: script/validatingapp.sh
      timeout: 300
      runas: ec2-user