# This is a basic workflow to help you get started with Actions

name: WOrkflow to validate Packer file

# Controls when the workflow will run
on:
  # Triggers the workflow on very pull request that is on the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: requiredtests
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    strategy:
      matrix:
        node-version: [12.x]
          
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run:  npm install
      - run:  npm run build --if-present
      # - run:  npm test

      # Packer commands to check whether packer is validated, pull request is merged only if packer is validated.
      - name: Packer initialization
        run:  packer init packerfinal.pkr.hcl
      - name: Validating packer
        run:  packer validate -syntax-only -var-file="devvars.pkrvars.hcl" packerfinal.pkr.hcl